In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
          'amazing restraunt',
          'too good',
          'terrible experience',
          'just loved it!',
          'will go again',
          'horrible food',
          'never go there',
          'poor service',
          'awesome',
          'needs improvement']

sentiment = np.array([1,1,1,0,1,1,0,0,0,1,0])

In [3]:
one_hot("finger licking good", 90)

[43, 3, 23]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[27, 25], [17, 11], [26, 27], [16, 27], [28, 28, 7], [13, 5, 23], [6, 25], [6, 5, 5], [8, 28], [1], [22, 13]]


WE WILL USE PADDING SO THAT MY EACH OF THE REVIEW IS HAVING SAME DIMENSION.

In [5]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length, padding = 'post')
padded_reviews

array([[27, 25,  0],
       [17, 11,  0],
       [26, 27,  0],
       [16, 27,  0],
       [28, 28,  7],
       [13,  5, 23],
       [ 6, 25,  0],
       [ 6,  5,  5],
       [ 8, 28,  0],
       [ 1,  0,  0],
       [22, 13,  0]], dtype=int32)

In [6]:
embedded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length = max_length, name = 'embedding'))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

Metal device set to: Apple M1


2022-12-10 23:29:34.264864: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-12-10 23:29:34.264971: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [7]:
X = padded_reviews
y = sentiment

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten (Flatten)           (None, 12)                0         
                                                                 
 dense (Dense)               (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.fit(X, y, epochs=50)

Epoch 1/50


2022-12-10 23:29:34.381625: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-12-10 23:29:34.565784: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 338ms/step - loss: 0.6946 - accuracy: 0.4545
Epoch 2/50
1/1 [==============================] - 0s 10ms/step - loss: 0.6934 - accuracy: 0.5455
Epoch 3/50
1/1 [==============================] - 0s 8ms/step - loss: 0.6922 - accuracy: 0.6364
Epoch 4/50
1/1 [==============================] - 0s 10ms/step - loss: 0.6910 - accuracy: 0.6364
Epoch 5/50
1/1 [==============================] - 0s 9ms/step - loss: 0.6898 - accuracy: 0.6364
Epoch 6/50
1/1 [==============================] - 0s 9ms/step - loss: 0.6887 - accuracy: 0.6364
Epoch 7/50
1/1 [==============================] - 0s 10ms/step - loss: 0.6875 - accuracy: 0.6364
Epoch 8/50
1/1 [==============================] - 0s 9ms/step - loss: 0.6863 - accuracy: 0.6364
Epoch 9/50
1/1 [==============================] - 0s 8ms/step - loss: 0.6851 - accuracy: 0.6364
Epoch 10/50
1/1 [==============================] - 0s 8ms/step - loss: 0.6840 - accuracy: 0.6364
Epoch 11/50
1/1 [============================

LETS SEE THE EMBEDDING LAYER

In [10]:
model.get_layer('embedding').get_weights()[0]

array([[ 0.08995157,  0.00398041, -0.09805339, -0.09132376],
       [-0.0337316 , -0.04149512, -0.03281473,  0.05566481],
       [-0.0409645 ,  0.01551295, -0.04242596,  0.038341  ],
       [-0.02991394, -0.03821014,  0.04051678, -0.02928272],
       [ 0.0175998 ,  0.01052628,  0.0416143 , -0.02916038],
       [ 0.03547469,  0.0618756 ,  0.06995948, -0.06116479],
       [ 0.0457557 ,  0.03858076,  0.03396819, -0.02944526],
       [-0.07976067, -0.00744309, -0.00669948,  0.07347894],
       [ 0.05210226,  0.0506585 ,  0.03139286, -0.09542403],
       [-0.02242916, -0.04860463,  0.04190916, -0.00056602],
       [-0.0178737 , -0.01522591,  0.01617045,  0.02944832],
       [ 0.01484676,  0.03164242, -0.07231846, -0.08332946],
       [-0.02568569, -0.00434846, -0.04905519,  0.04218486],
       [-0.08720085, -0.02306551, -0.02480881,  0.04417701],
       [-0.00467841,  0.02969016, -0.02223718,  0.02633424],
       [ 0.02802278, -0.0149386 , -0.00275352,  0.03677714],
       [ 0.07675673,  0.

In [11]:
weights = model.get_layer('embedding').get_weights()[0]

In [12]:
weights[17]

array([-0.04946142, -0.01717516, -0.04329364,  0.07812497], dtype=float32)

In [13]:
weights[1]

array([-0.0337316 , -0.04149512, -0.03281473,  0.05566481], dtype=float32)

SELF-SUPERVISED LEARNING:

WE ONLY HAVE A PARAGRAPH AND WE RUN A CBOW(CONTINUOUS BAG OF WORDS) - 3-4 MOVING WINDOW AND WE TRAIN THE MODEL.

## WORD2VEC

In [1]:
import gensim
import pandas as pd

In [2]:
df = pd.read_json("reviews_Cell_Phones_and_Accessories_5.json", lines=True)
df.head()

reviewerID        asin      reviewerName helpful  \
0  A30TL5EWN6DFXT  120401325X         christina  [0, 0]   
1   ASY55RVNIL0UD  120401325X          emily l.  [0, 0]   
2  A2TMXE2AFO7ONB  120401325X             Erica  [0, 0]   
3   AWJ0WZQYMYFQ4  120401325X                JM  [4, 4]   
4   ATX7CZYFXI1KW  120401325X  patrice m rogoza  [2, 3]   

                                          reviewText  overall  \
0  They look good and stick good! I just don't li...        4   
1  These stickers work like the review says they ...        5   
2  These are awesome and make my phone look so st...        5   
3  Item arrived in great time and was in perfect ...        4   
4  awesome! stays on, and looks great. can be use...        5   

                                     summary  unixReviewTime   reviewTime  
0                                 Looks Good      1400630400  05 21, 2014  
1                      Really great product.      1389657600  01 14, 2014  
2                             LOVE LOVE LOVE      1403740800  06 26, 2014  
3                                      Cute!      1382313600  10 21, 2013  
4  leopard home button sticker for iphone 4s      1359849600   02 3, 2013

In [3]:
df.shape

(194439, 9)

In [4]:
df.reviewText[0]

"They look good and stick good! I just don't like the rounded shape because I was always bumping it and Siri kept popping up and it was irritating. I just won't buy a product like this again"

In [6]:
gensim.utils.simple_preprocess("They look good and stick good! I just don't like the rounded shape because I was always bumping it and Siri kept popping up and it was irritating. I just won't buy a product like this again")

['they',
 'look',
 'good',
 'and',
 'stick',
 'good',
 'just',
 'don',
 'like',
 'the',
 'rounded',
 'shape',
 'because',
 'was',
 'always',
 'bumping',
 'it',
 'and',
 'siri',
 'kept',
 'popping',
 'up',
 'and',
 'it',
 'was',
 'irritating',
 'just',
 'won',
 'buy',
 'product',
 'like',
 'this',
 'again']

GENSIM TOKENIZES THE TEXT. CONVERTS A SENTENCE INTO LIST OF WORDS AND TOKENIZES IT.

In [8]:
review_text = df.reviewText.apply(gensim.utils.simple_preprocess)

In [9]:
review_text

0         [they, look, good, and, stick, good, just, don...
1         [these, stickers, work, like, the, review, say...
2         [these, are, awesome, and, make, my, phone, lo...
3         [item, arrived, in, great, time, and, was, in,...
4         [awesome, stays, on, and, looks, great, can, b...
                                ...                        
194434    [works, great, just, like, my, original, one, ...
194435    [great, product, great, packaging, high, quali...
194436    [this, is, great, cable, just, as, good, as, t...
194437    [really, like, it, becasue, it, works, well, w...
194438    [product, as, described, have, wasted, lot, of...
Name: reviewText, Length: 194439, dtype: object

In [24]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2,
    workers=4
)

In [28]:
model.build_vocab(review_text, progress_per=1000)

In [29]:
model.epochs

5

In [30]:
model.train(review_text, total_examples=model.corpus_count, epochs = model.epochs)

(61507756, 83868975)

In [31]:
model.save('./word2vec-amazon-cell-accessories.model')

In [33]:
model.wv.most_similar('great')

[('fantastic', 0.8648405075073242),
 ('wonderful', 0.8151528239250183),
 ('good', 0.7767614126205444),
 ('awesome', 0.7538857460021973),
 ('fabulous', 0.7224146127700806),
 ('perfect', 0.7135080695152283),
 ('excellent', 0.7109954357147217),
 ('terrific', 0.6869812607765198),
 ('amazing', 0.6828851103782654),
 ('nice', 0.6742976903915405)]

In [38]:
model.wv.similarity(w1='awesome', w2='good')

0.57934976

### Distributed Training

In [50]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

In [40]:
(X_train, y_train), (X_test, y_test) = datasets.cifar10.load_data()

In [41]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [42]:
X_train.shape

(50000, 32, 32, 3)

In [43]:
X_test.shape

(10000, 32, 32, 3)

In [44]:
classes = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

In [45]:
y_train[:5]

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [46]:
X_train = X_train/255
X_test = X_test/255

In [51]:
y_train_categorical = keras.utils.to_categorical(
    y_train, num_classes=10, dtype='float32'
)
y_test_categorical = keras.utils.to_categorical(
    y_test, num_classes=10, dtype='float32'
)

In [52]:
def get_model():
    model = keras.Sequential([
        layers.Flatten(input_shape=(32,32,3)),
        layers.Dense(3000, activation='relu'),
        layers.Dense(1000, activation='relu'),
        layers.Dense(10, activation='sigmoid')
    ])

    model.compile(optimizer='SGD',
                 loss = 'sparse_categorical_crossentropy',
                 metrics=['accuracy'])
    
    return model

In [54]:
train_tf_dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train_categorical))
test_tf_dataset = tf.data.Dataset.from_tensor_slices((X_test, y_test_categorical))

Metal device set to: Apple M1


2022-12-11 17:06:11.456389: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-12-11 17:06:11.457538: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [55]:
type(test_tf_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

LETS IMPLEMENT TF MIRROR STRATEGY. DIVIDING THE DATASET INTO MULTIPLE GPU

In [57]:
strategy = tf.distribute.MirroredStrategy()

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)


In [58]:
strategy.num_replicas_in_sync

1

In [61]:
BATCH_SIZE_PER_REPLICA = 1000
BATCH_SIZE = BATCH_SIZE_PER_REPLICA * strategy.num_replicas_in_sync

train_dataset = train_tf_dataset.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
test_dataset = test_tf_dataset.batch(BATCH_SIZE)

In [ ]:
%%timeit -n1 -r1
with strategy.scope():
    gpu_model = get_model()
    gpu_model.fit(train_dataset, epochs=10)